set_property IOSTANDARD LVCMOS33 [get_ports key_0]
set_property IOSTANDARD LVCMOS33 [get_ports key_state_0]
set_property PACKAGE_PIN W15 [get_ports key_0]
set_property PACKAGE_PIN V13 [get_ports key_state_0]


set_property PACKAGE_PIN F7 [get_ports SCLK_0]
set_property PACKAGE_PIN E7 [get_ports SDOUT_0]
set_property PACKAGE_PIN D7 [get_ports SDATA_GRP1_0]
set_property PACKAGE_PIN D6 [get_ports SDATA_GRP2_0]
set_property PACKAGE_PIN E8 [get_ports SEN_GRP1_0]
set_property PACKAGE_PIN D8 [get_ports SEN_GRP2_0]
set_property IOSTANDARD LVCMOS18 [get_ports SCLK_0]
set_property IOSTANDARD LVCMOS18 [get_ports SDATA_GRP1_0]
set_property IOSTANDARD LVCMOS18 [get_ports SDATA_GRP2_0]
set_property IOSTANDARD LVCMOS18 [get_ports SDOUT_0]
set_property IOSTANDARD LVCMOS18 [get_ports SEN_GRP1_0]
set_property IOSTANDARD LVCMOS18 [get_ports SEN_GRP2_0]

set_property PACKAGE_PIN G8 [get_ports TXRESET_0]
set_property IOSTANDARD LVCMOS18 [get_ports TXRESET_0]



set_property PACKAGE_PIN B7 [get_ports CW_EN_0]
set_property PACKAGE_PIN B6 [get_ports DSEL_0_0]
set_property PACKAGE_PIN A7 [get_ports DSEL_1_0]
set_property IOSTANDARD LVCMOS18 [get_ports CW_EN_0]
set_property IOSTANDARD LVCMOS18 [get_ports DSEL_0_0]
set_property IOSTANDARD LVCMOS18 [get_ports DSEL_1_0]
set_property PACKAGE_PIN B8 [get_ports STDBY_0]
set_property IOSTANDARD LVCMOS18 [get_ports STDBY_0]
set_property IOSTANDARD LVCMOS18 [get_ports TR_EN1_0]
set_property IOSTANDARD LVCMOS18 [get_ports TR_EN2_0]
set_property IOSTANDARD LVCMOS18 [get_ports TR_EN3_0]
set_property IOSTANDARD LVCMOS18 [get_ports TR_EN4_0]
set_property PACKAGE_PIN D3 [get_ports TR_EN1_0]
set_property PACKAGE_PIN C3 [get_ports TR_EN2_0]
set_property PACKAGE_PIN A2 [get_ports TR_EN3_0]
set_property PACKAGE_PIN A1 [get_ports TR_EN4_0]

set_property PACKAGE_PIN W12 [get_ports key_1]
set_property IOSTANDARD LVCMOS33 [get_ports key_1]
set_property PACKAGE_PIN V14 [get_ports key_state_1]
set_property IOSTANDARD LVCMOS33 [get_ports key_state_1]

set_property PACKAGE_PIN V15 [get_ports led_0]
set_property PACKAGE_PIN G7 [get_ports SCLK_1]
set_property IOSTANDARD LVCMOS18 [get_ports SCLK_1]
set_property IOSTANDARD LVCMOS33 [get_ports led_0]
set_property PACKAGE_PIN E5 [get_ports SDATA_GRP1_1]
set_property PACKAGE_PIN G6 [get_ports SDATA_GRP2_1]
set_property IOSTANDARD LVCMOS18 [get_ports SDATA_GRP1_1]
set_property IOSTANDARD LVCMOS18 [get_ports SDATA_GRP2_1]
set_property PACKAGE_PIN F5 [get_ports SDOUT_1]
set_property IOSTANDARD LVCMOS18 [get_ports SDOUT_1]
set_property PACKAGE_PIN F6 [get_ports SEN_GRP1_1]
set_property PACKAGE_PIN C8 [get_ports SEN_GRP2_1]
set_property IOSTANDARD LVCMOS18 [get_ports SEN_GRP1_1]
set_property IOSTANDARD LVCMOS18 [get_ports SEN_GRP2_1]
set_property PACKAGE_PIN D1 [get_ports TR_EN1_1]
set_property IOSTANDARD LVCMOS18 [get_ports TR_EN1_1]
set_property PACKAGE_PIN C1 [get_ports TR_EN2_1]
set_property IOSTANDARD LVCMOS18 [get_ports TR_EN2_1]
set_property PACKAGE_PIN E2 [get_ports TR_EN3_1]
set_property IOSTANDARD LVCMOS18 [get_ports TR_EN3_1]
set_property PACKAGE_PIN D2 [get_ports TR_EN4_1]
set_property IOSTANDARD LVCMOS18 [get_ports TR_EN4_1]

set_property PACKAGE_PIN C6 [get_ports TR_BF_SYNCP_0]
set_property PACKAGE_PIN D5 [get_ports TR_BF_SYNCP_1]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports TR_BF_SYNCP_0]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports TR_BF_SYNCP_1]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]

set_property PACKAGE_PIN AA20 [get_ports {GPIO_0_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
