# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.srcs/sources_1/bd/system/ip/system_delay_profile_module_0_0/system_delay_profile_module_0_0.xci
# IP: The module: 'system_delay_profile_module_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.srcs/sources_1/ip/tx1_delay_profile_rom/tx1_delay_profile_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tx1_delay_profile_rom || ORIG_REF_NAME==tx1_delay_profile_rom} -quiet] -quiet

# IP: D:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.srcs/sources_1/ip/tx0_delay_profile_rom/tx0_delay_profile_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tx0_delay_profile_rom || ORIG_REF_NAME==tx0_delay_profile_rom} -quiet] -quiet

# XDC: d:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.gen/sources_1/ip/tx1_delay_profile_rom/tx1_delay_profile_rom_ooc.xdc

# XDC: d:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.gen/sources_1/ip/tx0_delay_profile_rom/tx0_delay_profile_rom_ooc.xdc

# XDC: d:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.gen/sources_1/bd/system/ip/system_delay_profile_module_0_0/system_delay_profile_module_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_delay_profile_module_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.srcs/sources_1/bd/system/ip/system_delay_profile_module_0_0/system_delay_profile_module_0_0.xci
# IP: The module: 'system_delay_profile_module_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.srcs/sources_1/ip/tx1_delay_profile_rom/tx1_delay_profile_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tx1_delay_profile_rom || ORIG_REF_NAME==tx1_delay_profile_rom} -quiet] -quiet

# IP: D:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.srcs/sources_1/ip/tx0_delay_profile_rom/tx0_delay_profile_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tx0_delay_profile_rom || ORIG_REF_NAME==tx0_delay_profile_rom} -quiet] -quiet

# XDC: d:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.gen/sources_1/ip/tx1_delay_profile_rom/tx1_delay_profile_rom_ooc.xdc

# XDC: d:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.gen/sources_1/ip/tx0_delay_profile_rom/tx0_delay_profile_rom_ooc.xdc

# XDC: d:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.gen/sources_1/bd/system/ip/system_delay_profile_module_0_0/system_delay_profile_module_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_delay_profile_module_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
