# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# IP: ip/tx1_delay_profile_rom/tx1_delay_profile_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tx1_delay_profile_rom || ORIG_REF_NAME==tx1_delay_profile_rom} -quiet] -quiet

# IP: ip/tx0_delay_profile_rom/tx0_delay_profile_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tx0_delay_profile_rom || ORIG_REF_NAME==tx0_delay_profile_rom} -quiet] -quiet

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_0/system_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_0 || ORIG_REF_NAME==system_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/system/ip/system_key_module_0_0/system_key_module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_key_module_0_0 || ORIG_REF_NAME==system_key_module_0_0} -quiet] -quiet

# IP: bd/system/ip/system_key_module_1_0/system_key_module_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_key_module_1_0 || ORIG_REF_NAME==system_key_module_1_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/system_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_ila_0_1 || ORIG_REF_NAME==system_system_ila_0_1} -quiet] -quiet

# IP: bd/system/ip/system_led_flash_0_0/system_led_flash_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_led_flash_0_0 || ORIG_REF_NAME==system_led_flash_0_0} -quiet] -quiet

# IP: bd/system/ip/system_vio_0_0/system_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_vio_0_0 || ORIG_REF_NAME==system_vio_0_0} -quiet] -quiet

# IP: bd/system/ip/system_delay_profile_module_0_0/system_delay_profile_module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_delay_profile_module_0_0 || ORIG_REF_NAME==system_delay_profile_module_0_0} -quiet] -quiet

# IP: ip/tx1_delay_profile_rom/tx1_delay_profile_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tx1_delay_profile_rom || ORIG_REF_NAME==tx1_delay_profile_rom} -quiet] -quiet

# IP: ip/tx0_delay_profile_rom/tx0_delay_profile_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tx0_delay_profile_rom || ORIG_REF_NAME==tx0_delay_profile_rom} -quiet] -quiet

# IP: bd/system/ip/system_tx7332_config_module_0_0/system_tx7332_config_module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tx7332_config_module_0_0 || ORIG_REF_NAME==system_tx7332_config_module_0_0} -quiet] -quiet

# IP: bd/system/ip/system_tx7332_config_module_1_0/system_tx7332_config_module_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tx7332_config_module_1_0 || ORIG_REF_NAME==system_tx7332_config_module_1_0} -quiet] -quiet

# XDC: d:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.gen/sources_1/ip/tx1_delay_profile_rom/tx1_delay_profile_rom_ooc.xdc

# XDC: d:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.gen/sources_1/ip/tx0_delay_profile_rom/tx0_delay_profile_rom_ooc.xdc

# XDC: d:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.gen/sources_1/ip/tx1_delay_profile_rom/tx1_delay_profile_rom_ooc.xdc

# XDC: d:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.gen/sources_1/ip/tx0_delay_profile_rom/tx0_delay_profile_rom_ooc.xdc

# XDC: d:/MyProjects/zynq_prj/ultrasound_beamformer/ultrasound_beamformer.gen/sources_1/bd/system/system_ooc.xdc
